replicaCount: 1

image:
  repository: shreyasksrao/todoapi:latest

service:
  type: NodePort
  port: 8081
  name: svctodoh2api
  targetPort: 8081

container:
  name: todoapimysql

env:
  name: MYSQL_HOST

database:
  enabled: true
  disabled: false